# Central Angles of the E-Module
![E mod](http://www.rwgrayprojects.com/synergetics/s09/figs/f86411b.gif)

<div style="text-align: center">
[Fig. 986.411B](http://www.rwgrayprojects.com/synergetics/s09/figs/f86411b.html)
</div>

By:   
 * David Koski (trig) 
 * Kirby Urner (python)

The T & E modules have the same angles.  120 Ts (60 left, 60 right) build a Rhombic Triacontahedron of tetravolume 5, whereas 120 Es build a Rhombic Triacontahedron of radius 1. 

The Tmod RT has a slightly shorter radius of ~0.9994 versus 1.0.  Its volume is therefore a bit less as well.

![T mod](http://www.rwgrayprojects.com/synergetics/s09/figs/f86419.gif)

<div style="text-align: center">
[Fig. 986.419](http://www.rwgrayprojects.com/synergetics/s09/figs/f86419.html)
</div>

Per David Koski's research:

<pre>
The three central angles of the E module are:
a = 31.717474411º
b = 37.377368140º
c = 20.905157447º
these three sum to 90º

These are broken down into three  angles, one remains the same:
c = 20.905157447º
d = 13.282525588º
e = 10.812316963º
c + e = a
2d + e = b

Now we introduce three even smaller angles:
f = 7.622631859º
g = 5.659893729º
h = 5.152423234º
g + h = e
f + g = d
2f + g = c

It follows that:
a = 2f + 2g + h
b = 2f + 3g + h
c = 2f + g

The arctangents of the 8 angles described above:
a = 31.717474º  = arctan(Ø^-1)       = arctan(0.618034)
b = 37.377368º  = arctan(2Ø^-2)      = arctan(0.763932)
c = 20.905157º  = arctan(Ø^-2)       = arctan(0.381966)
d = 13.282525º  = arctan(Ø^-3)       = arctan(0.236068)
e = 10.812316º  = arctan(Ø^-2/2)     = arctan(0.190983)
f = 7.622631º   = arctan((2√5-3)/11) = arctan(0.133830)
g = 5.659893º   = arctan((5√5-9)/22) = arctan(0.099106)
h = 5.152423º   = arctan(Ø^-5)       = arctan(0.090169)
</pre>

In [1]:
from IPython.display import HTML 
import numpy as np
import pandas as pd
import numpy.testing as npt
from math import atan, tan, degrees, radians, sqrt

In [2]:
rt5 = sqrt(5)
Ø = (1 + rt5)/2

f = atan((2*rt5 - 3)/11)
g = atan((5*rt5 - 9)/22)
h = atan(Ø ** -5)

Per David's comments above: f, g, h serve as basis angles such that linear combinations thereof net additional angles a-e.

<pre>
a = 2f + 2g + h
b = 2f + 3g + h
c = 2f + g
d = f + g
e = g + h
</pre>

In [3]:
m = np.array([f, g, h]).reshape(3,1)
m

array([[0.13304002],
       [0.09878378],
       [0.08992675]])

In [4]:
coeffs = np.array([[2,2,1],[2,3,1],[2,1,0],[1,1,0],[0,1,1]])
coeffs

array([[2, 2, 1],
       [2, 3, 1],
       [2, 1, 0],
       [1, 1, 0],
       [0, 1, 1]])

In [5]:
coeffs.dot(m)

array([[0.55357436],
       [0.65235814],
       [0.36486383],
       [0.2318238 ],
       [0.18871053]])

In [6]:
a,b,c,d,e = coeffs.dot(m).ravel()

In [7]:
np.array([a,b,c,d,e,f,g,h]).reshape(8,1)

array([[0.55357436],
       [0.65235814],
       [0.36486383],
       [0.2318238 ],
       [0.18871053],
       [0.13304002],
       [0.09878378],
       [0.08992675]])

In [8]:
col1 = pd.Series(data=[a,b,c,d,e,f,g,h], index=['a','b','c','d','e','f','g','h'])

In [9]:
col1

a    0.553574
b    0.652358
c    0.364864
d    0.231824
e    0.188711
f    0.133040
g    0.098784
h    0.089927
dtype: float64

In [10]:
col2 = np.degrees(col1)  # convert radians to degrees

In [26]:
df = pd.concat([col1, col2], axis=1)  # build a 2-column dataframe

In [27]:
df.rename(columns={0: 'Radians', 1: 'Degrees'}, inplace=True) # renaming columns

In [28]:
df

Radians    Degrees
a  0.553574  31.717474
b  0.652358  37.377368
c  0.364864  20.905157
d  0.231824  13.282526
e  0.188711  10.812317
f  0.133040   7.622632
g  0.098784   5.659894
h  0.089927   5.152423

In [14]:
np.sum(df.loc[['a','b','c'],['Degrees']])

Degrees    90.0
dtype: float64

In [15]:
col0 = np.tan(col1)  # work back from radians

In [16]:
col0

a    0.618034
b    0.763932
c    0.381966
d    0.236068
e    0.190983
f    0.133831
g    0.099106
h    0.090170
dtype: float64

<pre>
The arctangents of the 8 angles described above:
a = 31.717474º  = arctan(Ø^-1)       = arctan(0.618034)
b = 37.377368º  = arctan(2Ø^-2)      = arctan(0.763932)
c = 20.905157º  = arctan(Ø^-2)       = arctan(0.381966)
d = 13.282525º  = arctan(Ø^-3)       = arctan(0.236068)
e = 10.812316º  = arctan(Ø^-2/2)     = arctan(0.190983)
f = 7.622631º   = arctan((2√5-3)/11) = arctan(0.133830)
g = 5.659893º   = arctan((5√5-9)/22) = arctan(0.099106)
h = 5.152423º   = arctan(Ø^-5)       = arctan(0.090169)
</pre>

In [17]:
phi_expr = pd.Series([Ø**-1, 2*Ø**-2, Ø**-2, Ø**-3, 
                     (Ø**-2)/2,(2*rt5-3)/11, (5*rt5-9)/22, Ø**-5],
                    index=['a','b','c','d','e','f','g','h'])
phi_expr

a    0.618034
b    0.763932
c    0.381966
d    0.236068
e    0.190983
f    0.133831
g    0.099106
h    0.090170
dtype: float64

In [18]:
df = pd.concat([phi_expr, col0, col1, col2], axis=1)

In [19]:
df.rename(columns={0: "Phi Expr", 1: "Arctan of...", 2: 'Radians', 3: 'Degrees'}, inplace=True)

In [20]:
df

Phi Expr  Arctan of...   Radians    Degrees
a  0.618034      0.618034  0.553574  31.717474
b  0.763932      0.763932  0.652358  37.377368
c  0.381966      0.381966  0.364864  20.905157
d  0.236068      0.236068  0.231824  13.282526
e  0.190983      0.190983  0.188711  10.812317
f  0.133831      0.133831  0.133040   7.622632
g  0.099106      0.099106  0.098784   5.659894
h  0.090170      0.090170  0.089927   5.152423